server {
    listen 80;
    server_name __ALIAS__;
    include /etc/nginx/snippets/acme.conf;
    include /etc/nginx/snippets/security_headers.conf;
    include /etc/nginx/snippets/proxy_app.conf;
}

server {
    listen 443 ssl;
    http2 on;
    server_name __ALIAS__;
    ssl_certificate __SSL_CERTIFICATE__;
    ssl_certificate_key __SSL_CERTIFICATE_KEY__;
    ssl_protocols TLSv1.2 TLSv1.3;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    include /etc/nginx/snippets/security_headers.conf;
    include /etc/nginx/snippets/proxy_app.conf;
}
