import type { SearchDocument } from "./types";

/** Catalogue statique des pages / services / actions INFOLOG. */
export const staticSearchCatalog: SearchDocument[] = [
  {
    id: "home",
    title: "Accueil INFOLOG",
    description:
      "Partenaire technologique des entreprises en Mauritanie et en Afrique.",
    category: "Pages",
    keywords: ["accueil", "infolog", "entreprise", "mauritanie"],
    type: "page",
    url: "/",
    priority: 100,
  },
  {
    id: "about",
    title: "Qui sommes-nous",
    description:
      "Présentation d'INFOLOG, mission, présence régionale et engagements.",
    category: "Pages",
    keywords: ["presentation", "entreprise", "a propos", "mission", "infolog"],
    type: "page",
    url: "/qui-sommes-nous",
    priority: 95,
  },
  {
    id: "national-cash",
    title: "National Cash",
    description:
      "Microfinance agréée BCM : crédits, épargnes, agences et inclusion financière.",
    category: "Services",
    keywords: [
      "national cash",
      "nc",
      "caisse",
      "microfinance",
      "credit",
      "epargne",
      "bcm",
    ],
    type: "service",
    url: "/qui-sommes-nous/national-cash",
    priority: 98,
  },
  {
    id: "national-cash-action",
    title: "Accéder au site National Cash",
    description: "Ouvrir le site officiel nationalcash.mr.",
    category: "Actions",
    keywords: ["national cash", "site", "caisse"],
    type: "action",
    url: "https://nationalcash.mr",
    priority: 70,
  },
  {
    id: "infogerance",
    title: "Infogérance",
    description:
      "Formules d'assistance pour gérer et sécuriser votre infrastructure IT.",
    category: "Services",
    keywords: ["infogerance", "assistance", "maintenance", "sla", "support"],
    type: "service",
    url: "/infogerance",
    priority: 90,
  },
  {
    id: "monetique",
    title: "Monétique",
    description:
      "Terminaux, GAB NCR, hotline et maintenance monétique pour partenaires bancaires.",
    category: "Services",
    keywords: ["monetique", "gab", "atm", "ncr", "paiement", "carte"],
    type: "service",
    url: "/monetique",
    priority: 90,
  },
  {
    id: "erp",
    title: "Progiciel ERP",
    description: "Intégration ERP, dont SAP, de l'analyse à la maintenance.",
    category: "Services",
    keywords: ["erp", "sap", "progiciel", "logiciel", "gestion"],
    type: "service",
    url: "/progiciel-erp",
    priority: 88,
  },
  {
    id: "btp",
    title: "BTP",
    description:
      "Entreprise générale de bâtiment : gros œuvre, second œuvre, génie civil.",
    category: "Services",
    keywords: [
      "btp",
      "construction",
      "batiment",
      "chantier",
      "genie civil",
      "maconnerie",
    ],
    type: "service",
    url: "/btp",
    image: "/brand/btp-hero.png",
    priority: 92,
  },
  {
    id: "telephonie",
    title: "Téléphonie",
    description:
      "Distribution Samsung Galaxy, smartphones, tablettes et SAV INFOLOG.",
    category: "Services",
    keywords: [
      "telephonie",
      "telephone",
      "smartphone",
      "mobile",
      "galaxy",
      "samsung",
    ],
    type: "service",
    url: "/telephonie",
    priority: 96,
  },
  {
    id: "izi-shop",
    title: "IZI SHOP",
    description:
      "Smartphones Galaxy à crédit jusqu'à 6 mois — service IZICALL / National Cash Plus.",
    category: "Services",
    keywords: [
      "izi shop",
      "izicall",
      "credit",
      "telephone",
      "smartphone",
      "samsung",
    ],
    type: "service",
    url: "/telephonie/izi-shop",
    priority: 94,
  },
  {
    id: "izi-shop-action",
    title: "Accéder à IZI SHOP",
    description: "Ouvrir la boutique izicall.shop.",
    category: "Actions",
    keywords: ["izi shop", "izicall", "acheter", "souscrire"],
    type: "action",
    url: "https://izicall.shop",
    priority: 68,
  },
  {
    id: "electromenager",
    title: "Électroménager",
    description:
      "Équipements Samsung : cuisson, froid, multimédia — professionnels et particuliers.",
    category: "Équipements",
    keywords: [
      "electromenager",
      "samsung",
      "froid",
      "cuisson",
      "refrigerateur",
      "tv",
      "imprimante",
    ],
    type: "service",
    url: "/electromenager",
    priority: 90,
  },
  {
    id: "data-center",
    title: "Data center",
    description:
      "Modernisation et simplification du datacenter, infrastructures virtualisées.",
    category: "Informatique",
    keywords: ["data center", "datacenter", "serveur", "infrastructure", "cloud"],
    type: "service",
    url: "/data-center",
    priority: 85,
  },
  {
    id: "securite",
    title: "Sécurité",
    description:
      "Pare-feu, antivirus managé, filtrage web et politique de droits d'accès.",
    category: "Informatique",
    keywords: ["securite", "firewall", "antivirus", "cyber", "protection"],
    type: "service",
    url: "/securite",
    priority: 85,
  },
  {
    id: "collaboration",
    title: "Collaboration",
    description:
      "Réseaux LAN/WAN et outils de collaboration : ToIP, visioconférence, messagerie.",
    category: "Informatique",
    keywords: ["collaboration", "reseau", "voip", "visioconference", "messagerie"],
    type: "service",
    url: "/collaboration",
    priority: 82,
  },
  {
    id: "ged",
    title: "GED",
    description: "Gestion électronique de documents — intégration INFOLOG.",
    category: "Informatique",
    keywords: ["ged", "documents", "archivage", "dematerialisation"],
    type: "service",
    url: "/ged",
    priority: 80,
  },
  {
    id: "virtualisation-serveurs",
    title: "Virtualisation de serveurs",
    description: "Virtualisation serveurs VMware, Hyper-V et environnements complexes.",
    category: "Informatique",
    keywords: ["virtualisation", "serveur", "vmware", "hyper-v"],
    type: "service",
    url: "/virtualisation-serveurs",
    priority: 80,
  },
  {
    id: "virtualisation-postes",
    title: "Virtualisation de postes et d'applications",
    description: "Postes virtuels, Citrix, RDS et clients légers.",
    category: "Informatique",
    keywords: ["virtualisation", "poste", "citrix", "rds", "vdi"],
    type: "service",
    url: "/virtualisation-postes",
    priority: 80,
  },
  {
    id: "pearson-vue",
    title: "Pearson VUE & E-Learning",
    description:
      "Centre de test agréé Pearson VUE et formation e-learning.",
    category: "Formation",
    keywords: ["pearson", "vue", "certification", "examen", "elearning", "formation"],
    type: "service",
    url: "/pearson-vue",
    priority: 84,
  },
  {
    id: "e-learning",
    title: "E-Learning Center",
    description: "Apprendre à son rythme avec modules et évaluations.",
    category: "Formation",
    keywords: ["elearning", "formation", "modules", "apprentissage"],
    type: "section",
    url: "/pearson-vue#e-learning",
    section: "e-learning",
    priority: 78,
  },
  {
    id: "centre-appel",
    title: "Centre d'appel",
    description:
      "Plateforme call center 24/7 pour relation client et prospection.",
    category: "Services",
    keywords: ["call center", "centre d appel", "hotline", "relation client"],
    type: "service",
    url: "/centre-appel",
    priority: 83,
  },
  {
    id: "transformation-it",
    title: "Transformation IT",
    description: "Socle innovant pour accompagner la transformation digitale.",
    category: "Informatique",
    keywords: ["transformation", "digitale", "it", "innovation"],
    type: "service",
    url: "/transformation-it",
    priority: 78,
  },
  {
    id: "affichage-dynamique",
    title: "Affichage dynamique",
    description:
      "Diffusion de messages sur écrans pour halls, points de vente et établissements.",
    category: "Informatique",
    keywords: ["affichage", "dynamique", "ecran", "digital signage"],
    type: "service",
    url: "/affichage-dynamique",
    priority: 76,
  },
  {
    id: "installation-telephonique",
    title: "Installation téléphonique pour entreprise",
    description:
      "Standards téléphoniques, VoIP, PABX/IPBX et CTI pour entreprises.",
    category: "Services",
    keywords: ["installation", "telephonie", "voip", "pabx", "ipbx", "entreprise"],
    type: "service",
    url: "/installation-telephonique",
    priority: 82,
  },
  {
    id: "energie",
    title: "Énergie",
    description:
      "Consultation, ingénierie et équipements de mesure — partenariat Siemens.",
    category: "Équipements",
    keywords: ["energie", "siemens", "mesure", "ingenierie"],
    type: "service",
    url: "/energie",
    priority: 80,
  },
  {
    id: "contact",
    title: "Nous contacter",
    description:
      "Formulaire, téléphones, e-mail et adresse INFOLOG à Nouakchott.",
    category: "Actions",
    keywords: [
      "contact",
      "contacter",
      "joindre",
      "coordonnees",
      "email",
      "telephone",
      "adresse",
    ],
    type: "action",
    url: "/contact",
    priority: 97,
  },
  {
    id: "pole-it",
    title: "Solutions IT & Digital",
    description:
      "Pôle IT : infogérance, datacenter, sécurité, collaboration, GED, ERP.",
    category: "Pôles",
    keywords: ["informatique", "it", "digital", "solutions"],
    type: "pole",
    url: "/solutions-it-digital",
    priority: 75,
  },
  {
    id: "pole-finance",
    title: "Monétique & Finance",
    description: "Pôle finance : monétique, GAB et National Cash.",
    category: "Pôles",
    keywords: ["finance", "monetique", "national cash"],
    type: "pole",
    url: "/monetique-finance",
    priority: 75,
  },
  {
    id: "pole-support",
    title: "Formation & Support",
    description: "Pearson VUE, e-learning, centre d'appel et téléphonie.",
    category: "Pôles",
    keywords: ["formation", "support", "telephonie"],
    type: "pole",
    url: "/formation-support",
    priority: 74,
  },
  {
    id: "pole-industrie",
    title: "BTP & Électroménager",
    description: "Bâtiment, électroménager Samsung et énergie.",
    category: "Pôles",
    keywords: ["btp", "electromenager", "energie", "equipements"],
    type: "pole",
    url: "/btp-electromenager",
    priority: 74,
  },
];
