add_header X-Robots-Tag "noindex, nofollow" always;
add_header X-Frame-Options "DENY" always;

location = / {
    return 302 $scheme://$host/admin;
}

location = /admin/login {
    limit_req zone=login burst=5 nodelay;
    include /etc/nginx/snippets/proxy_params;
    proxy_pass http://web:3000;
}

location = /admin/mot-de-passe-oublie {
    limit_req zone=login burst=5 nodelay;
    include /etc/nginx/snippets/proxy_params;
    proxy_pass http://web:3000;
}
